SET IDENTITY_INSERT [dbo].[TablaLocalidad] ON
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (1, N'Villa allende')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (2, N'Achiras')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (3, N'Adelia María')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (4, N'Agua de Oro')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (5, N'Alcira')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (6, N'Aldea Santa María')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (7, N'Alejandro Roca')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (8, N'Alejo Ledesma')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (9, N'Alicia')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (10, N'Almafuerte')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (11, N'Alpa Corral')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (12, N'Alta Gracia')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (13, N'Alto Alegre')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (14, N'Alto de los Quebrachos')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (15, N'Altos de Chipión')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (16, N'Amboy')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (17, N'Ámbul')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (18, N'Ana Zumarán')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (19, N'Anisacate')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (20, N'Arias')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (21, N'Arroyito')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (22, N'Arroyo Algodón')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (23, N'Arroyo Cabral')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (24, N'Arroyo Los Patos')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (25, N'Ascochinga')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (26, N'Assunta')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (27, N'Atahona')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (28, N'Ausonia')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (29, N'Avellaneda')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (30, N'Ballesteros')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (31, N'Ballesteros Sur')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (32, N'Balnearia')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (33, N'Bañado de Soto')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (34, N'Barrio Gilbert')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (35, N'Barrio Nuevo Rio Ceballos')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (36, N'Barrio Santa Isabel')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (37, N'Bell Ville')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (38, N'Bengolea')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (39, N'Benjamín Gould')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (40, N'Berrotarán')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (41, N'Bialet Massé')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (42, N'Bouwer')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (43, N'Brinkmann')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (44, N'Bulnes')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (45, N'Cabalango')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (46, N'Calchín')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (47, N'Calchín Oeste')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (48, N'Camilo Aldao')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (49, N'Caminiaga')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (50, N'Campos del Virrey')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (51, N'Cañada del Sauce')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (52, N'Cañada de Luque')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (53, N'Cañada de Machado')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (54, N'Cañada de Río Pinto')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (55, N'Canals')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (56, N'Candelaria Sur')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (57, N'Canteras El Sauce')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (58, N'Canteras Quilpo')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (59, N'Capilla del Carmen')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (60, N'Capilla de Sitón')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (61, N'Capilla Vieja')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (62, N'Capitán General Bernardo O''Higgins')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (63, N'Carnerillo')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (64, N'Carrilobo')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (65, N'Casa Bamba')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (66, N'Casa Grande')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (67, N'Caseros Centro')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (68, N'Causana')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (69, N'Cavanagh')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (70, N'Cerro Colorado')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (71, N'Chaján')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (72, N'Chalacea')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (73, N'Chañar Viejo')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (74, N'Chancaní')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (75, N'Charbonier')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (76, N'Charras')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (77, N'Chazón')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (78, N'Chilibroste')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (79, N'Chucul')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (80, N'Chuña')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (81, N'Chuña Huasi')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (82, N'Churqui Cañada')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (83, N'Ciénaga del Coro')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (84, N'Cintra')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (85, N'Colazo')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (86, N'Colonia 10 de Julio')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (87, N'Colonia Almada')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (88, N'Colonia Anita')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (89, N'Colonia Barge')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (90, N'Colonia Bismarck')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (91, N'Colonia Bremen')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (92, N'Colonia Caroya')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (93, N'Colonia Italiana')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (94, N'Colonia Iturraspe')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (95, N'Colonia Las Cuatro Esquinas')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (96, N'Colonia Las Pichanas')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (97, N'Colonia Marina')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (98, N'Colonia Prosperidad')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (99, N'Colonia San Bartolomé')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (100, N'Colonia San Pedro')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (101, N'Colonia Santa María')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (102, N'Colonia Tirolesa')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (103, N'Colonia Valtelina')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (104, N'Colonia Veinticinco')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (105, N'Colonia Vicente Agüero')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (106, N'Colonia Videla')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (107, N'Colonia Vignaud')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (108, N'Conlara')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (109, N'Copacabana')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (110, N'Córdoba')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (111, N'Coronel Baigorria')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (112, N'Coronel Moldes')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (113, N'Corral de Bustos')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (114, N'Corralito')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (115, N'Corral Quemado')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (116, N'Cosquín')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (117, N'Costa Azul')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (118, N'Costa Sacate')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (119, N'Country Chacras de la Villa ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (120, N'Cruz Alta')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (121, N'Cruz Caña')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (122, N'Cruz de Caña')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (123, N'Cruz del Eje')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (124, N'Cuesta Blanca')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (125, N'Dalmacio Vélez')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (126, N'Deán Funes')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (127, N'Del Campillo')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (128, N'Despeñaderos')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (129, N'Devoto')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (130, N'Diego de Rojas')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (131, N'Dique Chico')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (132, N'Dos Arroyos')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (133, N'El Alcalde')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (134, N'El Arañado')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (135, N'El Brete')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (136, N'El Chacho')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (137, N'El Corcovado')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (138, N'El Crispín')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (139, N'El Durazno')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (140, N'Elena')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (141, N'El Fortín')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (142, N'El Fuertecito')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (143, N'El Huayco')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (144, N'El Manzano')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (145, N'El Pantanillo')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (146, N'El Potrerillo')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (147, N'El Rastreador')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (148, N'El Rincón')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (149, N'El Rodeo')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (150, N'El Tío')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (151, N'El Tuscal')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (152, N'Embalse')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (153, N'Esquina')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (154, N'Esquina del Alambre')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (155, N'Estación Colonia Tirolesa')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (156, N'Estación Lecueder')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (157, N'Estación Luxardo')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (158, N'NULLEstancia de Guadalupe')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (159, N'Estancia Vieja')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (160, N'Etruria')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (161, N'Eufrasio Loza')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (162, N'Eufrasio Loza')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (163, N'Falda del Carmen')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (164, N'Freyre')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (165, N'General Baldissera')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (166, N'General Cabrera')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (167, N'General Deheza')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (168, N'General Fotheringham')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (169, N'General Levalle')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (170, N'General Paz')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (171, N'General Roca')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (172, N'Guanaco Muerto')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (173, N'Guasapampa')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (174, N'Guatimozín')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (175, N'Gutemberg')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (176, N'Hernando')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (177, N'Hipólito Bouchard')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (178, N'Huanchillas')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (179, N'Huerta Grande')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (180, N'Huinca Renancó')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (181, N'Idiazábal')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (182, N'Impira')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (183, N'Inriville')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (184, N'Isla Verde')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (185, N'Italó')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (186, N'James Craik')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (187, N'Jesús María')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (188, N'José de la Quintana')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (189, N'Justiniano Posse')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (190, N'Kilómetro 658')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (191, N'La Banda')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (192, N'La Batea')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (193, N'La Boca del Río')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (194, N'Laborde')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (195, N'Laboulaye')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (196, N'La Calera')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (197, N'La Carbonada')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (198, N'La Carlota')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (199, N'La Carolina')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (200, N'La Cautiva')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (201, N'La Cesira')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (202, N'La Cortadera')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (203, N'La Cruz')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (204, N'La Cumbre')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (205, N'La Cumbrecita')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (206, N'La Falda')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (207, N'La Francia')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (208, N'La Gilda')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (209, N'La Granja')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (210, N'Laguna Larga')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (211, N'La Higuera')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (212, N'La Laguna')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (213, N'La Morada')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (214, N'La Paisanita')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (215, N'La Palestina')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (216, N'La Pampa')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (217, N'La Paquita')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (218, N'La Para')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (219, N'La Paz')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (220, N'La Perla')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (221, N'La Playa')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (222, N'La Playosa')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (223, N'La Población')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (224, N'La Posta')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (225, N'La Puerta')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (226, N'La Quinta')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (227, N'La Ramada')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (228, N'La Rancherita y Las Cascadas')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (229, N'La Rinconada')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (230, N'Las Acequias')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (231, N'Las Albahacas')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (232, N'Las Arrias')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (233, N'Las Bajadas')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (234, N'Las Caleras')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (235, N'Las Calles')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (236, N'Las Cañadas')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (237, N'Las Chacras')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (238, N'Las Corzuelas')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (239, N'La Serranita')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (240, N'Las Gramillas')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (241, N'Las Higueras')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (242, N'Las Isletillas')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (243, N'Las Mojarras')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (244, N'Las Oscuras')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (245, N'Las Palmas')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (246, N'Las Peñas')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (247, N'Las Perdices')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (248, N'Las Playas')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (249, N'Las Rabonas')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (250, N'Las Saladas')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (251, N'Las Tapias')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (252, N'Las Varas')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (253, N'Las Varillas')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (254, N'Las Vertientes')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (255, N'La Tordilla')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (256, N'La Travesía')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (257, N'Leguizamón')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (258, N'Leones')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (259, N'Loma Bola')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (260, N'Los Callejones')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (261, N'Los Cedros')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (262, N'Los Cerrillos')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (263, N'Los Chañaritos')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (264, N'Los Cisnes')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (265, N'Los Cocos')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (266, N'Los Cóndores')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (267, N'Los Hornillos')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (268, N'Los Hoyos')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (269, N'Los Mistoles')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (270, N'Los Molinos')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (271, N'Los Molles')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (272, N'Los Pozos')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (273, N'Los Reartes')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (274, N'Los Surgentes')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (275, N'Los Talares')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (276, N'Los Zorros')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (277, N'Lozada')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (278, N'Luca')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (279, N'Lucio V. Mansilla')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (280, N'Luque')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (281, N'Lutti')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (282, N'Luyaba')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (283, N'Malagueño')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (284, N'Malena')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (285, N'Mallín')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (286, N'Malvinas Argentinas')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (287, N'Manfredi')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (288, N'Maquinista Gallini')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (289, N'Marcos Juárez')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (290, N'Marull')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (291, N'Matorrales')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (292, N'Mattaldi')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (293, N'Mayu Sumaj')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (294, N'Media Naranja')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (295, N'Melo')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (296, N'Mendiolaza')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (297, N'Mi Granja')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (298, N'Mina Clavero')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (299, N'Miramar')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (300, N'Monte Buey')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (301, N'Monte Cristo')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (302, N'Monte de los Gauchos')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (303, N'Monte del Rosario')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (304, N'Monte Leña')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (305, N'Monte Maíz')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (306, N'Monte Ralo')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (307, N'Morrison')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (308, N'Morteros')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (309, N'Mussi')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (310, N'Nicolás Bruzzone')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (311, N'Noetinger')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (312, N'Nono')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (313, N'Obispo Trejo')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (314, N'Olaeta')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (315, N'Oliva')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (316, N'Olivares de San Nicolás')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (317, N'Onagoity')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (318, N'Oncativo')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (319, N'Ordóñez')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (320, N'Pacheco de Melo')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (321, N'Pajas Blancas')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (322, N'Pampayasta Norte')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (323, N'Pampayasta Sur')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (324, N'Panaholma')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (325, N'Parque Calmayo')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (326, N'Pascanas')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (327, N'Pasco')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (328, N'Paso del Durazno')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (329, N'Paso Viejo')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (330, N'Pilar')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (331, N'Pincén')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (332, N'Piquillín')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (333, N'Plaza de Mercedes')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (334, N'Plaza Luxardo')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (335, N'Plaza San Francisco')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (336, N'Porteña')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (337, N'Potrero de Garay')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (338, N'Pozo del Molle')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (339, N'Pozo Nuevo')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (340, N'Pueblo Comechingones')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (341, N'Pueblo Italiano')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (342, N'Puesto de Castro')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (343, N'Punta del Agua')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (344, N'Quebracho Herrado')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (345, N'Quebracho Ladeado')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (346, N'Quebrada de los Pozos')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (347, N'Quebrada de Luna')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (348, N'Quilino')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (349, N'Rafael García')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (350, N'Ramón J. Cárcano')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (351, N'Ranqueles')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (352, N'Rayo Cortado')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (353, N'Rincón')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (354, N'Río Bamba')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (355, N'Río Ceballos')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (356, N'Río Cuarto')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (357, N'Río de los Sauces')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (358, N'Río Primero')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (359, N'Río Segundo')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (360, N'Río Tercero')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (361, N'Rosales')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (362, N'Rosario del Saladillo')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (363, N'Sacanta')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (364, N'Sagrada Familia')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (365, N'Saira')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (366, N'Saladillo')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (367, N'Saldán')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (368, N'Salsacate')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (369, N'Salsipuedes')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (370, N'Sampacho')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (371, N'Sanabria')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (372, N'San Agustín')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (373, N'San Antonio de Arredondo')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (374, N'San Antonio de Litín')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (375, N'San Basilio')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (376, N'San Carlos Minas')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (377, N'San Clemente')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (378, N'San Esteban')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (379, N'San Francisco')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (380, N'San Francisco del Chañar')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (381, N'San Gerónimo')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (382, N'San Huberto')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (383, N'San Ignacio')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (384, N'San Javier y Yacanto')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (385, N'San Joaquín')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (386, N'San José')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (387, N'San José de la Dormida')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (388, N'San José de las Salinas')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (389, N'San Lorenzo')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (390, N'San Marcos')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (391, N'San Marcos Sierra')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (392, N'San Martín')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (393, N'San Nicolás ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (394, N'San Pedro')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (395, N'San Pedro de Gütemberg')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (396, N'San Pedro de Toyos')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (397, N'San Pedro Norte')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (398, N'San Roque')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (399, N'San Severo')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (400, N'Santa Catalina ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (401, N'Santa Catalina')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (402, N'Santa Elena')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (403, N'Santa Eufemia')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (404, N'Santa Magdalena ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (405, N'Santa María de Punilla')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (406, N'Santa Rosa de Calamuchita')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (407, N'Santa Rosa de Río Primero')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (408, N'Santiago Temple')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (409, N'San Vicente')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (410, N'Sarmiento')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (411, N'Saturnino María Laspiur')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (412, N'Sauce Arriba')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (413, N'Sebastián Elcano')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (414, N'Seeber')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (415, N'Segunda Usina')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (416, N'Serrano')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (417, N'Serrezuela')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (418, N'Silvio Pellico')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (419, N'Simbolar')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (420, N'Sinsacate')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (421, N'Socavones')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (422, N'Solar de los Molinos')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (423, N'Suco')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (424, N'Tala Cañada')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (425, N'Tala Huasi')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (426, N'Talaini')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (427, N'Tancacha')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (428, N'Taninga')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (429, N'Tanti')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (430, N'Tasna')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (431, N'Ticino')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (432, N'Tinoco')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (433, N'Tío Pujio')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (434, N'Toledo')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (435, N'Toro Pujio')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (436, N'Tosno')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (437, N'Tosquitas')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (438, N'Tránsito')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (439, N'Tuclame')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (440, N'Ucacha')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (441, N'Unquillo')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (442, N'Valle Alegre')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (443, N'Valle de Anisacate')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (444, N'Valle Hermoso')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (445, N'Viamonte')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (446, N'Vicuña Mackenna')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (447, N'Villa Albertina')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (448, N'Villa Alpina')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (449, N'Villa Amancay')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (450, N'Villa Ascasubi')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (451, N'Villa Berna')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (452, N'Villa Candelaria')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (453, N'Villa Carlos Paz')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (454, N'Villa Cerro Azul')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (455, N'Villa Ciudad de América')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (456, N'Villa Ciudad Parque Los Reartes')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (457, N'Villa Concepción del Tío')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (458, N'Villa Corazon de Maria')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (459, N'Villa Cura Brochero')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (460, N'Villa de Las Rosas')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (461, N'Villa del Dique')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (462, N'Villa del Prado')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (463, N'Villa del Rosario')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (464, N'Villa del Totoral')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (465, N'Villa del Tránsito')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (466, N'Villa de María')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (467, N'Villa de Pocho')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (468, N'Villa de Soto')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (469, N'Villa Dolores')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (470, N'Villa El Chacay')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (471, N'Villa El Fachinal')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (472, N'Villa Elisa')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (473, N'Villa El Tala')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (474, N'Villa Flor Serrana')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (475, N'Villa Fontana')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (476, N'Villa General Belgrano')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (477, N'Villa Giardino')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (478, N'Villa Gutiérrez')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (479, N'Villa Huidobro')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (480, N'Villa La Bolsa')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (481, N'Villa Lago Azul')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (482, N'Villa La Rivera')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (483, N'Villa La Viña')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (484, N'Villa Los Aromos')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (485, N'Villa Los Llanos')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (486, N'Villa Los Patos')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (487, N'Villa María')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (488, N'Villa Nueva')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (489, N'Villa Oeste')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (490, N'Villa Parque Santa Ana')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (491, N'Villa Parque Síquiman')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (492, N'Villa Quillinzo')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (493, N'Villa Reducción')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (494, N'Villa Río Icho Cruz')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (495, N'Villa Rossi')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (496, N'Villa Rumipal')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (497, N'Villa San Esteban')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (498, N'Villa San Isidro')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (499, N'Villa San José ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (500, N'Villa Santa Cruz del Lago')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (501, N'Villa Santa Eugenia')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (502, N'Villa Sarmiento')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (503, N'Villa Sarmiento')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (504, N'Villa Sierras de Oro')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (505, N'Villa Tulumba')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (506, N'Villa Valeria')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (507, N'Villa Yacanto')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (508, N'Washington')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (509, N'Wenceslao Escalante')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (510, N'Yocsina')
SET IDENTITY_INSERT [dbo].[TablaLocalidad] OFF
