SET IDENTITY_INSERT [dbo].[TablaDepartamento] ON
INSERT INTO [dbo].[TablaDepartamento] ([Id], [NombreDepartamento]) VALUES (1, N'')
INSERT INTO [dbo].[TablaDepartamento] ([Id], [NombreDepartamento]) VALUES (2, N'Capital')
INSERT INTO [dbo].[TablaDepartamento] ([Id], [NombreDepartamento]) VALUES (3, N'Colón')
INSERT INTO [dbo].[TablaDepartamento] ([Id], [NombreDepartamento]) VALUES (4, N'Cruz del Eje')
INSERT INTO [dbo].[TablaDepartamento] ([Id], [NombreDepartamento]) VALUES (5, N'General Roca')
INSERT INTO [dbo].[TablaDepartamento] ([Id], [NombreDepartamento]) VALUES (6, N'General San Martín	')
INSERT INTO [dbo].[TablaDepartamento] ([Id], [NombreDepartamento]) VALUES (7, N'Ischilín')
INSERT INTO [dbo].[TablaDepartamento] ([Id], [NombreDepartamento]) VALUES (8, N'Juárez Celman')
INSERT INTO [dbo].[TablaDepartamento] ([Id], [NombreDepartamento]) VALUES (9, N'Marcos Juárez')
INSERT INTO [dbo].[TablaDepartamento] ([Id], [NombreDepartamento]) VALUES (10, N'Minas')
INSERT INTO [dbo].[TablaDepartamento] ([Id], [NombreDepartamento]) VALUES (11, N'Pocho')
INSERT INTO [dbo].[TablaDepartamento] ([Id], [NombreDepartamento]) VALUES (12, N'Presidente Roque Sáenz Peña')
INSERT INTO [dbo].[TablaDepartamento] ([Id], [NombreDepartamento]) VALUES (13, N'Punilla')
INSERT INTO [dbo].[TablaDepartamento] ([Id], [NombreDepartamento]) VALUES (14, N'Río Cuarto')
INSERT INTO [dbo].[TablaDepartamento] ([Id], [NombreDepartamento]) VALUES (15, N'Río Primero')
INSERT INTO [dbo].[TablaDepartamento] ([Id], [NombreDepartamento]) VALUES (16, N'Río Seco')
INSERT INTO [dbo].[TablaDepartamento] ([Id], [NombreDepartamento]) VALUES (17, N'Río Segundo')
INSERT INTO [dbo].[TablaDepartamento] ([Id], [NombreDepartamento]) VALUES (18, N'San Alberto')
INSERT INTO [dbo].[TablaDepartamento] ([Id], [NombreDepartamento]) VALUES (19, N'San Javier')
INSERT INTO [dbo].[TablaDepartamento] ([Id], [NombreDepartamento]) VALUES (20, N'San Justo')
INSERT INTO [dbo].[TablaDepartamento] ([Id], [NombreDepartamento]) VALUES (21, N'Santa María')
INSERT INTO [dbo].[TablaDepartamento] ([Id], [NombreDepartamento]) VALUES (22, N'Sobremonte')
INSERT INTO [dbo].[TablaDepartamento] ([Id], [NombreDepartamento]) VALUES (23, N'Tercero Arriba')
INSERT INTO [dbo].[TablaDepartamento] ([Id], [NombreDepartamento]) VALUES (24, N'Totoral')
INSERT INTO [dbo].[TablaDepartamento] ([Id], [NombreDepartamento]) VALUES (25, N'Tulumba')
INSERT INTO [dbo].[TablaDepartamento] ([Id], [NombreDepartamento]) VALUES (26, N'Unión')
SET IDENTITY_INSERT [dbo].[TablaDepartamento] OFF
