SET IDENTITY_INSERT [dbo].[TablaLocalidad] ON
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (1, N'Achiras')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (2, N'Alpa Corral')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (3, N'Agua de oro')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (4, N'Adelia María')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (5, N'Alcira Gigena')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (6, N'Alejandro Roca')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (7, N'Alejo Ledesma')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (8, N'Alicia ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (9, N'Almafuerte ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (10, N'Alta Gracia')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (11, N'Alto Resbaloso')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (12, N'Anisacate')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (13, N'Arias ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (14, N'Arroyito ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (15, N'Arroyo Cabral')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (16, N'Ballesteros ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (17, N'Balnearia')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (18, N'Berrotarán ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (19, N'Bialet Massé')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (20, N'Brinkmann')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (21, N'Calchín ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (22, N'Camilo Aldao')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (23, N'Canals ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (24, N'Casa Grande ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (25, N'Colonia La Argentina ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (26, N'Córdoba ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (27, N'Coronel Moldes ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (28, N'Corral de Bustos')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (29, N'Corralito ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (30, N'Cruz Alta ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (31, N'Cuesta Blanca ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (32, N'Del Campillo')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (33, N'Despeñaderos')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (34, N'Devoto ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (35, N'Dolores -')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (36, N'El Pueblito ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (37, N'Elena ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (38, N'Estación Juárez Celman')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (39, N'Etruria ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (40, N'Freyre')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (41, N'General Baldissera')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (42, N'General Cabrera')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (43, N'General Deheza')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (44, N'General Levalle')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (45, N'General Roca ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (46, N'Guatimozín ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (47, N'Hernando ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (48, N'Huerta Grande')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (49, N'Huinca Renancó')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (50, N'Inriville')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (51, N'Isla Verde ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (52, N'James Craik')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (53, N'José de la Quintana ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (54, N'Jovita ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (55, N'Justiniano Posse ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (56, N'La Carlota ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (57, N'La Cumbre ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (58, N'La Falda')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (59, N'La Francia')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (60, N'La Para')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (61, N'La Paz ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (62, N'La Perla ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (63, N'La Población ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (64, N'La Rancherita')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (65, N'La Serranita')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (66, N'Laborde ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (67, N'Laboulaye')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (68, N'Laguna Larga')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (69, N'Las Acequias')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (70, N'Las Chacras ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (71, N'Las Chacras')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (72, N'Las Higueras')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (73, N'Las Perdices')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (74, N'Las Tapias')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (75, N'Leones ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (76, N'Los Cerrillos ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (77, N'Los Cocos')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (78, N'Los Romeros ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (79, N'Los Surgentes')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (80, N'Luque ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (81, N'Malagueño ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (82, N'Marcos Juárez')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (83, N'Mayu Sumaj')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (84, N'Mina Clavero')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (85, N'Molinari ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (86, N'Monte Buey')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (87, N'Monte Cristo')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (88, N'Monte Maíz')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (89, N'Morrison ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (90, N'Morteros ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (91, N'Noetinger')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (92, N'Oliva ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (93, N'Oncativo')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (94, N'Ordóñez ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (95, N'Pascanas')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (96, N'Paso del Durazno')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (97, N'Pilar ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (98, N'La Playosa')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (99, N'Porteña')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (100, N'Pozo del Molle')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (101, N'Quilino')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (102, N'Río Primero ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (103, N'Río Segundo ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (104, N'Rumi Huasi')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (105, N'Sacanta')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (106, N'Sampacho')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (107, N'San Antonio de Arredondo')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (108, N'San Basilio ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (109, N'San Esteban ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (110, N'San Francisco del Chañar')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (111, N'San José de la Dormida')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (112, N'San Marcos Sud')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (113, N'San Pedro ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (114, N'San Roque ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (115, N'Santa Catalina ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (116, N'Santa María de Punilla')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (117, N'Santa Mónica ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (118, N'Santa Rosa de Río Primero')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (119, N'Santiago Temple')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (120, N'Saturnino María Laspiur ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (121, N'Sebastián Elcano ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (122, N'Serrano ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (123, N'Serrezuela ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (124, N'Tancacha')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (125, N'Tanti')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (126, N'Tío Pujio')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (127, N'Toledo ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (128, N'Tránsito ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (129, N'Ucacha')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (130, N'Valle de Anisacate')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (131, N'Valle Hermoso ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (132, N'Vicuña Mackenna ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (133, N'Villa Ascasubi')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (134, N'Villa Carlos Paz')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (135, N'Villa Cura Brochero')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (136, N'Villa de las Rosas')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (137, N'Villa de los Ranchos')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (138, N'Villa de María')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (139, N'Villa de Soto ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (140, N'Villa del Rosario (Córdoba)')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (141, N'Villa del Totoral')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (142, N'Villa Giardino')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (143, N'Villa Huidobro')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (144, N'Villa La Bolsa')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (145, N'Villa Los Aromos')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (146, N'Villa Nueva ')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (147, N'Villa Parque Síquiman')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (148, N'Villa Río Icho Cruz')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (149, N'Villa San Nicolás')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (150, N'Villa Santa Cruz del Lago')
INSERT INTO [dbo].[TablaLocalidad] ([Id], [NombreLocalidad]) VALUES (151, N'Villa Sarmiento ')
SET IDENTITY_INSERT [dbo].[TablaLocalidad] OFF