SET IDENTITY_INSERT [dbo].[TablaProvincia] ON
INSERT INTO [dbo].[TablaProvincia] ([Id], [NombreProvincia]) VALUES (1, N'Buenos Aires')
INSERT INTO [dbo].[TablaProvincia] ([Id], [NombreProvincia]) VALUES (2, N'Ciudad Autónoma de Buenos Aires')
INSERT INTO [dbo].[TablaProvincia] ([Id], [NombreProvincia]) VALUES (3, N'Catamarca')
INSERT INTO [dbo].[TablaProvincia] ([Id], [NombreProvincia]) VALUES (4, N'Chaco')
INSERT INTO [dbo].[TablaProvincia] ([Id], [NombreProvincia]) VALUES (5, N'Chubut')
INSERT INTO [dbo].[TablaProvincia] ([Id], [NombreProvincia]) VALUES (6, N'Córdoba')
INSERT INTO [dbo].[TablaProvincia] ([Id], [NombreProvincia]) VALUES (7, N'Corrientes')
INSERT INTO [dbo].[TablaProvincia] ([Id], [NombreProvincia]) VALUES (8, N'Entre Ríos')
INSERT INTO [dbo].[TablaProvincia] ([Id], [NombreProvincia]) VALUES (9, N'Formosa')
INSERT INTO [dbo].[TablaProvincia] ([Id], [NombreProvincia]) VALUES (10, N'Jujuy')
INSERT INTO [dbo].[TablaProvincia] ([Id], [NombreProvincia]) VALUES (11, N'La Pampa')
INSERT INTO [dbo].[TablaProvincia] ([Id], [NombreProvincia]) VALUES (12, N'La Rioja')
INSERT INTO [dbo].[TablaProvincia] ([Id], [NombreProvincia]) VALUES (13, N'Mendoza')
INSERT INTO [dbo].[TablaProvincia] ([Id], [NombreProvincia]) VALUES (14, N'Misiones')
INSERT INTO [dbo].[TablaProvincia] ([Id], [NombreProvincia]) VALUES (15, N'Neuquén')
INSERT INTO [dbo].[TablaProvincia] ([Id], [NombreProvincia]) VALUES (16, N'Río Negro')
INSERT INTO [dbo].[TablaProvincia] ([Id], [NombreProvincia]) VALUES (17, N'Salta')
INSERT INTO [dbo].[TablaProvincia] ([Id], [NombreProvincia]) VALUES (18, N'San Juan')
INSERT INTO [dbo].[TablaProvincia] ([Id], [NombreProvincia]) VALUES (19, N'San Luis')
INSERT INTO [dbo].[TablaProvincia] ([Id], [NombreProvincia]) VALUES (20, N'Santa Cruz')
INSERT INTO [dbo].[TablaProvincia] ([Id], [NombreProvincia]) VALUES (21, N'Santa Fe')
INSERT INTO [dbo].[TablaProvincia] ([Id], [NombreProvincia]) VALUES (22, N'Santiago del Estero')
INSERT INTO [dbo].[TablaProvincia] ([Id], [NombreProvincia]) VALUES (23, N'Tierra del Fuego')
INSERT INTO [dbo].[TablaProvincia] ([Id], [NombreProvincia]) VALUES (24, N'Tucumán')
SET IDENTITY_INSERT [dbo].[TablaProvincia] OFF